# Azure OpenAI API credentials
[azure_openai]
api_key = "FXKWeX5juTW9kTgGcv3H3rWladBJZGN3Jm7OWqOdONVtuLqx9gH4JQQJ99AKACfhMk5XJ3w3AAABACOGFVFg"
endpoint = "https://access-01.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-08-01-preview"
